arch: arm64
language: minimal
services: docker

before_install:
  - apt-get update
  # We use poppler-utils for converting pdf to png
  - apt-get install poppler-utils

before_script:
  # We use the docker image from https://hub.docker.com/r/dxjoke/tectonic-docker/
  - docker pull dxjoke/tectonic-docker

script:
  # Compile src/resume.tex and output to root of repo
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic src/resume.tex -o ./"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: resume.pdf
  cleanup: true
  on:
    tags: true

after_deploy:
  # Generate preview png
  - pdftoppm resume.pdf resume -png -f 1 -singlefile -rx 300 -ry 300
  # Push resume.png to master for preview in README.md
  - ./travis-push.sh
  # Trigger Netlify build after build pass which pulls latest release
  - curl -X POST -d {} https://api.netlify.com/build_hooks/$NETLIFY_BUILD_HOOK